#!/usr/bin/env ruby

require 'httparty'
require 'dotenv/load'
require 'thor'
require 'benchmark'
require 'reverse_markdown'

cli_files = File.join(File.dirname(__FILE__), 'cli', '*.rb')
solution_files = File.join(File.dirname(__FILE__), 'solutions', '**', '*.rb')
Dir[cli_files].each { |file| require file }
Dir[solution_files].each { |file| require file }

# The CLI application
class Aoc < Thor
  desc 'download YEAR DAY', 'downloads an input file'
  method_option :download, aliases: '-d'
  def download(year, day)
    PuzzleInput.download(year, day)
  end

  desc 'bootstrap YEAR DAY', 'prepares a sample project for a given day:
downloads the input, creates a sample source and spec file'
  method_option :bootstrap, aliases: '-b'
  def bootstrap(year, day)
    ::PuzzleInput.download(year, day)
    Template.create_templates(year, day)
    puts "https://adventofcode.com/#{year}/day/#{day}"
  end

  desc 'run YEAR DAY', 'executes a given day/year'
  method_option :run_day, aliases: '-r'
  def run_day(year, day)
    puzzle = PuzzleSource.create_puzzle(year, day)
    input_path = PuzzleInput.load(year, day)
    url = "https://adventofcode.com/#{year}/day/#{day}"
    PuzzleSource.run_part('Part One', url) { puzzle.part_1(input_path) }
    puts
    PuzzleSource.run_part('Part Two', url) { puzzle.part_2(input_path) }
  end

  desc 'one YEAR DAY', 'executes the part_1 for a given day/year'
  method_option :one
  def one(year, day)
    puzzle = PuzzleSource.create_puzzle(year, day)
    input_path = PuzzleInput.load(year, day)
    url = "https://adventofcode.com/#{year}/day/#{day}"
    PuzzleSource.run_part('Part One', url) { puzzle.part_1(input_path) }
  end

  desc 'two YEAR DAY', 'executes the part_2 for a given day/year'
  method_option :two
  def two(year, day)
    puzzle = PuzzleSource.create_puzzle(year, day)
    input_path = PuzzleInput.load(year, day)
    url = "https://adventofcode.com/#{year}/day/#{day}"
    PuzzleSource.run_part('Part Two', url) { puzzle.part_2(input_path) }
  end

  desc 'submit YEAR DAY', 'submits an answer for a given day/year'
  method_option :submit
  def submit(year, day, part)
    puzzle = PuzzleSource.create_puzzle(year, day)
    return unless puzzle
    input_path = PuzzleInput.load(year, day)
    answer = puzzle.send(:"part_#{part}", input_path)

    aoc_api = AocApi.new(ENV['AOC_COOKIE'])
    response = aoc_api.submit(year, day, part, answer)
    message = response.match(/(?<=<article>).+(?=<\/article>)/).to_s.strip
    markdown_message = ReverseMarkdown.convert(message)

    puts markdown_message
  end
end

Dotenv.load("#{__dir__}/.env")
Dotenv.require_keys('AOC_COOKIE', 'AOC_INPUT_DIRECTORY')
Aoc.start
